name: p300cnn
channels:
   - defaults
   - anaconda
   - conda-forge
dependencies:
   - python>=3.7
   - numpy
   - scipy
   - pandas
   - matplotlib
   - scikit-learn
   - cudatoolkit=10.0
   - cudnn
   - pip:
     - tensorflow-gpu==1.14.0