python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 0 
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 1
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 2
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 3
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 4
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 5
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 6
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 7
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject $1
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 9
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 10
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 11
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 12
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 13
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 14
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 15
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 16
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 17
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 1$1
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 19
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 20
python3 src/single_trial_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy models/within_subject/SepConv1D_$1/ --n_filters $1 --subject 21
