python3 src/cross_subject_BN3.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/BN3/
python3 src/cross_subject_OCLNN.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/OCLNN/
python3 src/cross_subject_CNN1.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/CNN1/
python3 src/cross_subject_CNN3.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/CNN3/
python3 src/cross_subject_CNNR.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/CNNR/
python3 src/cross_subject_UCNN1.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/UCNN1/
python3 src/cross_subject_UCNN3.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/UCNN3/
python3 src/cross_subject_EEGNet.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/EEGNet/
python3 src/cross_subject_ShallowConv1D.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/ShallowConvNet/
python3 src/cross_subject_DeepConvNet.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/DeepConvNet/
python3 src/cross_subject_SepConv1D.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/SepConv1D/
python3 src/cross_subject_FCNN.py data/data6_osv.npy data/labels6_osv.npy corrected_models/cross_subject/FCNN/
