python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/2/ --n_trials 2
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/3/ --n_trials 3
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/4/ --n_trials 4
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/5/ --n_trials 5
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/6/ --n_trials 6
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/7/ --n_trials 7
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/8/ --n_trials 8
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/9/ --n_trials 9
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/10/ --n_trials 10
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/11/ --n_trials 11
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/12/ --n_trials 12
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/13/ --n_trials 13
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/14/ --n_trials 14
python3 src/subject_model_promediacion.py data/data6_osv.npy data/labels6_osv.npy models/subject_dependent/multi_trial/15/ --n_trials 15
